language: common-lisp
sudo: false

env:
  global:
    - ROSWELL_INSTALL_DIR: $HOME/.roswell
    - PATH: $PATH:$HOME/.roswell/bin
    - COVERAGE_EXCLUDE: tests:roswell
  matrix:
    - LISP=sbcl COVERALLS=true
    - LISP=ccl-bin
    - LISP=abcl
    - LISP=ecl

install:
  - curl -L https://raw.githubusercontent.com/roswell/roswell/release/scripts/install-for-ci.sh | sh
  - ros install fukamachi/rove
  - git clone https://github.com/t-sin/rosa.git

before_script:
  - ros --version
  - ros config

script:
  - rove rosa.asd
